QUANTITY_PER_PAGE = 10

START, CITY, CITY_CHOICE, CATEGORY, PRICE = range(5)
FAVORITE, ADD_FAVORITE, DELETE_FAVORITE = range(5, 8)
COMMENT, ADD_COMMENT, COMMENT_INPUT, NEXT_PAGE = range(8, 12)

BUTTON_SEARCH = 'Поиск'
BUTTON_ABOUT = 'О боте'
BUTTON_FAVORITE = 'Избранное'
BUTTON_DELETE_USER = 'Удалить аккаунт'

BUTTON_SKIP = 'Пропустить'
BUTTON_NEXT = 'Далее'

BUTTON_ADD_FAVORITE = 'В избранное'
BUTTON_DELETE_FAVORITE = 'Удалить из избранного'
BUTTON_COMMENTS = 'Коментарии'
BUTTON_ADD_COMMENT = 'Добавить комментарий'
