# Generated by Django 5.0.6 on 2024-06-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID пользователя в Телеграм'),
        ),
    ]
