name: Flake8 Backend Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.0.0 pep8-naming==0.14.1 flake8-broken-line==1.0.0 flake8-return==1.2.0 flake8-isort==6.1.1 flake8-docstrings==1.7.0
          pip install -r ./backend/requirements.txt
      - name: Test backend with flake8
        run: |
          python -m flake8 --config ./backend/setup.cfg backend/

  send_message_after_backend_tests:
    name: Message after backend tests
    runs-on: ubuntu-latest
    needs:
      - backend_tests

    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Пулреквест проверен flake8.
          Репозитарий ${{ github.repository }}
          Разработчик ${{ github.actor }}
          Коммит ${{ github.sha }}
