name: Main PB workflow

on:
  push:
    branches:
      - 'prod'

jobs:
  build_backend_and_push_to_docker_hub:
    name: Push backend to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: vvvas/premium_product_bot_backend:latest
  
  build_gateway_and_push_to_docker_hub:
    name: Push gateway to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./gateway/
          push: true
          tags: vvvas/premium_product_bot_gateway:latest

  send_message_after_push_to_docker_hub:
    name: Message after push to DockerHub
    runs-on: ubuntu-latest
    needs:
      - build_backend_and_push_to_docker_hub
      - build_gateway_and_push_to_docker_hub

    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Образы бэка и гейта успешно отправлены на DockerHub. Разработчик ${{ github.actor }}. Коммит ${{ github.sha }}

  deploy:
    name: Deploy
    if: github.ref_name == 'prod'
    runs-on: ubuntu-latest
    needs: 
      - build_backend_and_push_to_docker_hub
      - build_gateway_and_push_to_docker_hub

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Copy docker-compose.prod.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "infra/docker-compose.prod.yml"
        target: "premium_product_bot"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd premium_product_bot
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d
          docker compose -f docker-compose.prod.yml exec backend python manage.py makemigrations
          docker compose -f docker-compose.prod.yml exec backend python manage.py migrate
          docker compose -f docker-compose.prod.yml exec backend python manage.py collectstatic --no-input
          docker compose -f docker-compose.prod.yml exec backend python manage.py set_webhook

  send_message_after_deploy:
    name: Message after deploy
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой успешно выполнен. Разработчик ${{ github.actor }}. Коммит ${{ github.sha }}
